//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAssignments_Log
    {
        public int LogId { get; set; }
        public string AssignmentId { get; set; }
        public string ActionType { get; set; }
        public System.DateTime ActionTimestamp { get; set; }
        public string PerformedBy { get; set; }
        public string Old_ReportingUnit { get; set; }
        public string Old_ProductionUnit { get; set; }
        public string Old_Shift { get; set; }
        public string Old_AttendanceType { get; set; }
        public string Old_EmployeeId { get; set; }
        public string Old_EmployeeName { get; set; }
        public string Old_Remarks { get; set; }
    }
}
