//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAssignments
    {
        public int assignment_id { get; set; }
        public string reporting_unit_ID { get; set; }
        public Nullable<System.Guid> 報工生產單位GUID { get; set; }
        public Nullable<System.Guid> 生產單位名稱GUID { get; set; }
        public Nullable<System.Guid> 班別GUID { get; set; }
        public Nullable<System.Guid> 出勤類型GUID { get; set; }
        public string employee_id { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
        public string current_editor { get; set; }
        public Nullable<System.DateTime> edit_lock_time { get; set; }
    
        public virtual HResources_人員 HResources_人員 { get; set; }
        public virtual HResources_出勤類型 HResources_出勤類型 { get; set; }
        public virtual HResources_生產單位名稱 HResources_生產單位名稱 { get; set; }
        public virtual HResources_班別 HResources_班別 { get; set; }
        public virtual HResources_報工生產單位 HResources_報工生產單位 { get; set; }
    }
}
