//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_MaterialGunInfo
    {
        public int sno { get; set; }
        public string MaterialGun_Eno { get; set; }
        public string MaterialGun_Sno { get; set; }
        public string MaterialGun_Trade { get; set; }
        public string MaterialGun_Size { get; set; }
        public Nullable<int> MaintainCycle { get; set; }
        public Nullable<System.DateTime> MaintainNexDate { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public Nullable<int> DiscardDesc { get; set; }
        public Nullable<bool> MaterialGunDiscard { get; set; }
        public Nullable<System.DateTime> DiscardDate { get; set; }
        public string DiscardOPId { get; set; }
        public Nullable<bool> DiscardCheck { get; set; }
        public string Mark { get; set; }
    }
}
