//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_MaterialGunRepair
    {
        public int sno { get; set; }
        public string MaterialGun_Eno { get; set; }
        public string MaterialGun_Sno { get; set; }
        public Nullable<System.DateTime> RepairDate { get; set; }
        public string RepairUserId { get; set; }
        public Nullable<int> BadDescription { get; set; }
        public Nullable<System.DateTime> MaintenanceTime { get; set; }
        public string MaintenanceUserId { get; set; }
        public Nullable<int> MaintenanceResult { get; set; }
        public Nullable<int> Classification { get; set; }
        public string Other { get; set; }
        public string ChangeItemName { get; set; }
        public string ChangeItemNo { get; set; }
        public string Mark { get; set; }
        public Nullable<bool> Chk { get; set; }
    }
}
