//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_MaterialCorrection
    {
        public int sno { get; set; }
        public string MaterialGun_Sno { get; set; }
        public string MaterialGun_Eno { get; set; }
        public string MaterialGun_Size { get; set; }
        public Nullable<bool> TestResult { get; set; }
        public Nullable<System.DateTime> CorrectionDate { get; set; }
        public string FileName { get; set; }
        public string operators { get; set; }
        public string memo { get; set; }
    }
}
