//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_Member
    {
        public ES_Member()
        {
            this.ES_MemberFunction = new HashSet<ES_MemberFunction>();
        }
    
        public int fId { get; set; }
        public string fUserId { get; set; }
        public string fPwd { get; set; }
        public string fName { get; set; }
        public Nullable<bool> fStatus { get; set; }
        public string Dept_No { get; set; }
        public string email { get; set; }
        public string classRoom { get; set; }
    
        public virtual ICollection<ES_MemberFunction> ES_MemberFunction { get; set; }
    }
}
