//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_QuoteForSales
    {
        public ES_QuoteForSales()
        {
            this.ES_QuoteUploadRecords = new HashSet<ES_QuoteUploadRecords>();
            this.ES_QuoteUploadFiles = new HashSet<ES_QuoteUploadFiles>();
        }
    
        public int sno { get; set; }
        public string CustNo { get; set; }
        public string SalesNo { get; set; }
        public string EngSr { get; set; }
        public string CustMaterial { get; set; }
        public Nullable<int> WoNoAttri { get; set; }
        public Nullable<System.DateTime> RequDate { get; set; }
        public string Mark { get; set; }
        public string SalesId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Chk { get; set; }
        public string OtherName { get; set; }
        public Nullable<bool> CancelChk { get; set; }
    
        public virtual ICollection<ES_QuoteUploadRecords> ES_QuoteUploadRecords { get; set; }
        public virtual ICollection<ES_QuoteUploadFiles> ES_QuoteUploadFiles { get; set; }
    }
}
