//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_QuoteUploadRecords
    {
        public ES_QuoteUploadRecords()
        {
            this.ES_QuoteUploadFiles = new HashSet<ES_QuoteUploadFiles>();
        }
    
        public int sno { get; set; }
        public Nullable<int> Q_sno { get; set; }
        public string Name { get; set; }
    
        public virtual ES_QuoteForSales ES_QuoteForSales { get; set; }
        public virtual ICollection<ES_QuoteUploadFiles> ES_QuoteUploadFiles { get; set; }
    }
}
