//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ES_QuoteForIE
    {
        public int sno { get; set; }
        public int id { get; set; }
        public string IEonwer { get; set; }
        public Nullable<System.DateTime> IEQuoteDate { get; set; }
        public Nullable<System.DateTime> IEQuoteTDate { get; set; }
        public Nullable<System.DateTime> OperatorDate { get; set; }
        public string IEMark { get; set; }
        public string IEStatus { get; set; }
    }
}
