//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESIntegrateSysEntities : DbContext
    {
        public ESIntegrateSysEntities()
            : base("name=ESIntegrateSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ES_Member> ES_Member { get; set; }
        public DbSet<ES_MemberRole> ES_MemberRole { get; set; }
        public DbSet<ES_MaterialGunBadDesc> ES_MaterialGunBadDesc { get; set; }
        public DbSet<ES_MaterialGunRepairClass> ES_MaterialGunRepairClass { get; set; }
        public DbSet<ES_MaterialGunInfo> ES_MaterialGunInfo { get; set; }
        public DbSet<ES_MaterialGunDiscardDesc> ES_MaterialGunDiscardDesc { get; set; }
        public DbSet<ES_MaintainWork> ES_MaintainWork { get; set; }
        public DbSet<ES_RoleClassification> ES_RoleClassification { get; set; }
        public DbSet<ES_DeptInfo> ES_DeptInfo { get; set; }
        public DbSet<ES_MemberLayout> ES_MemberLayout { get; set; }
        public DbSet<ES_QuoteForIE> ES_QuoteForIE { get; set; }
        public DbSet<ES_MaterialGunRepair> ES_MaterialGunRepair { get; set; }
        public DbSet<ES_MaterialCorrection> ES_MaterialCorrection { get; set; }
        public DbSet<ES_MaterialGunSize> ES_MaterialGunSize { get; set; }
        public DbSet<ES_QuoteWoNoAttri> ES_QuoteWoNoAttri { get; set; }
        public DbSet<ES_QuoteCust> ES_QuoteCust { get; set; }
        public DbSet<ES_QuoteForSales> ES_QuoteForSales { get; set; }
        public DbSet<ES_QuoteUploadRecords> ES_QuoteUploadRecords { get; set; }
        public DbSet<ES_QuoteUploadFiles> ES_QuoteUploadFiles { get; set; }
        public DbSet<ES_FunctionItem> ES_FunctionItem { get; set; }
        public DbSet<ES_MemberFunction> ES_MemberFunction { get; set; }
        public DbSet<ES_MaterialGunMResult> ES_MaterialGunMResult { get; set; }
        public DbSet<EmployeeAssignments_Log> EmployeeAssignments_Log { get; set; }
        public DbSet<人力配置授權表> 人力配置授權表 { get; set; }
        public DbSet<HResources_人員> HResources_人員 { get; set; }
        public DbSet<HResources_出勤類型> HResources_出勤類型 { get; set; }
        public DbSet<HResources_生產單位名稱> HResources_生產單位名稱 { get; set; }
        public DbSet<HResources_班別> HResources_班別 { get; set; }
        public DbSet<HResources_報工生產單位> HResources_報工生產單位 { get; set; }
        public DbSet<EmployeeAssignments> EmployeeAssignments { get; set; }
        public DbSet<ES_ReportingUnit> ES_ReportingUnit { get; set; }
        public DbSet<ES_ProductionUnit> ES_ProductionUnit { get; set; }
        public DbSet<AppMultiLanguageResources> AppMultiLanguageResources { get; set; }
    }
}
