//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HResources_班別
    {
        public HResources_班別()
        {
            this.EmployeeAssignments = new HashSet<EmployeeAssignments>();
        }
    
        public System.Guid GUID { get; set; }
        public string shift_ID { get; set; }
        public string 班別名稱 { get; set; }
        public bool 是否啟用 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string 生產單位班別 { get; set; }
    
        public virtual ICollection<EmployeeAssignments> EmployeeAssignments { get; set; }
    }
}
