//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESIntegrateSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 人力配置授權表
    {
        public int 授權ID { get; set; }
        public string 報工生產單位名稱 { get; set; }
        public string 授權者工號 { get; set; }
        public bool 狀態 { get; set; }
        public string 建立者 { get; set; }
        public Nullable<System.DateTime> 建立時間 { get; set; }
        public string 修改者 { get; set; }
        public Nullable<System.DateTime> 修改時間 { get; set; }
        public System.Guid 報工生產單位GUID { get; set; }
        public string 生產單位 { get; set; }
        public string 班別 { get; set; }
    }
}
